import test from "node:test";
import assert from "node:assert/strict";
import worker from "../src/index.js";
class MemoryKV { values = new Map(); async get(key, type) { const value = this.values.get(key); return type === "json" && value ? JSON.parse(value) : value ?? null; } async put(key, value) { this.values.set(key, value); } }
const origin = "https://pochita09.github.io", item_id = "a".repeat(64), env = () => ({ FEEDBACK: new MemoryKV() });
const body = (overrides = {}) => ({ item_id, topic_id: "ai-models", vote: "up", reason: null, score: 8, title: "Title", summary: "Summary", source: "Source", url: "https://example.com/article", ...overrides });
const request = (path, method, payload) => new Request(`https://worker.example${path}`, { method, headers: { Origin: origin, "Content-Type": "application/json" }, body: payload && JSON.stringify(payload) });
test("saves up feedback and returns it", async () => { const response = await worker.fetch(request("/feedback", "POST", body()), env()); assert.equal(response.status, 200); assert.equal((await response.json()).feedback.vote, "up"); });
test("updates one item instead of creating duplicates", async () => { const bindings = env(); await worker.fetch(request("/feedback", "POST", body()), bindings); await worker.fetch(request("/feedback", "POST", body({ vote: "down", reason: "既知" })), bindings); const feedback = (await (await worker.fetch(request("/feedback", "GET"), bindings)).json()).feedback; assert.equal(feedback.length, 1); assert.equal(feedback[0].reason, "既知"); });
test("rejects invalid vote and down vote without reason", async () => { const bindings = env(); assert.equal((await worker.fetch(request("/feedback", "POST", body({ vote: "other" })), bindings)).status, 400); assert.equal((await worker.fetch(request("/feedback", "POST", body({ vote: "down", reason: null })), bindings)).status, 400); });
test("gets item, handles missing data, and limits CORS", async () => { const bindings = env(); await worker.fetch(request("/feedback", "POST", body()), bindings); const found = await worker.fetch(request(`/feedback/${item_id}`, "GET"), bindings); assert.equal(found.status, 200); assert.equal(found.headers.get("Access-Control-Allow-Origin"), origin); assert.equal((await worker.fetch(request(`/feedback/${"b".repeat(64)}`, "GET"), bindings)).status, 404); assert.equal((await worker.fetch(new Request("https://worker.example/feedback", { headers: { Origin: "https://attacker.example" } }), bindings)).status, 403); });
