import test from "node:test";
import assert from "node:assert/strict";
import worker from "../src/index.js";
class MemoryKV { values = new Map(); async get(key, type) { const value = this.values.get(key); return type === "json" && value ? JSON.parse(value) : value ?? null; } async put(key, value) { this.values.set(key, value); } }
const origin = "https://pochita09.github.io", item_id = "a".repeat(64), env = () => ({ FEEDBACK: new MemoryKV() });
const body = (overrides = {}) => ({ item_id, topic_id: "ai-models", vote: "up", reason: null, score: 8, title: "Title", summary: "Summary", source: "Source", url: "https://example.com/article", ...overrides });
const request = (path, method, payload) => new Request(`https://worker.example${path}`, { method, headers: { Origin: origin, "Content-Type": "application/json" }, body: payload && JSON.stringify(payload) });
test("saves up feedback and returns it", async () => { const response = await worker.fetch(request("/feedback", "POST", body()), env()); assert.equal(response.status, 200); assert.equal((await response.json()).feedback.vote, "up"); });
test("updates one item instead of creating duplicates", async () => { const bindings = env(); await worker.fetch(request("/feedback", "POST", body()), bindings); await worker.fetch(request("/feedback", "POST", body({ vote: "down", reason: "既知" })), bindings); const feedback = (await (await worker.fetch(request("/feedback", "GET"), bindings)).json()).feedback; assert.equal(feedback.length, 1); assert.equal(feedback[0].reason, "既知"); });
test("rejects invalid vote and down vote without reason", async () => { const bindings = env(); assert.equal((await worker.fetch(request("/feedback", "POST", body({ vote: "other" })), bindings)).status, 400); assert.equal((await worker.fetch(request("/feedback", "POST", body({ vote: "down", reason: null })), bindings)).status, 400); });
test("gets item, handles missing data, and limits CORS", async () => { const bindings = env(); await worker.fetch(request("/feedback", "POST", body()), bindings); const found = await worker.fetch(request(`/feedback/${item_id}`, "GET"), bindings); assert.equal(found.status, 200); assert.equal(found.headers.get("Access-Control-Allow-Origin"), origin); assert.equal((await worker.fetch(request(`/feedback/${"b".repeat(64)}`, "GET"), bindings)).status, 404); assert.equal((await worker.fetch(new Request("https://worker.example/feedback", { headers: { Origin: "https://attacker.example" } }), bindings)).status, 403); });
const config = () => ({ topics: { "ai-models": { display_name: "モデル", criteria: "新しいAIモデルと重要なAPI変更を優先する。", threshold: 7, sources: { "openai-news": false, "deepmind-blog": true, "anthropic-news": true, "anthropic-research": true } } }, run: { keep_below_threshold: false, read_dim_enabled: true, telegram_enabled: true } });
test("returns default config, saves config, and returns it again", async () => { const bindings = env(); const initial = await worker.fetch(new Request("https://worker.example/config"), bindings); assert.equal(initial.status, 200); assert.equal((await initial.json()).config.topics["ai-models"].threshold, 6); const saved = await worker.fetch(request("/config", "PUT", config()), bindings); assert.equal(saved.status, 200); assert.equal((await saved.json()).config.run.keep_below_threshold, false); const reread = await worker.fetch(new Request("https://worker.example/config"), bindings); assert.equal((await reread.json()).config.topics["ai-models"].sources["openai-news"].enabled, false); });
test("rejects invalid config threshold and source", async () => { const bindings = env(); assert.equal((await worker.fetch(request("/config", "PUT", {}), bindings)).status, 400); const badThreshold = config(); badThreshold.topics["ai-models"].threshold = 11; assert.equal((await worker.fetch(request("/config", "PUT", badThreshold), bindings)).status, 400); const badSource = config(); badSource.topics["ai-models"].sources.bad = true; assert.equal((await worker.fetch(request("/config", "PUT", badSource), bindings)).status, 400); });
test("run.times is no longer part of the config contract", async () => { const bindings = env(); const initial = await (await worker.fetch(new Request("https://worker.example/config"), bindings)).json(); assert.equal(initial.config.run.times, undefined); const saved = await worker.fetch(request("/config", "PUT", config()), bindings); assert.equal(saved.status, 200); assert.equal((await saved.json()).config.run.times, undefined); });
test("rejects a topic that drops a standard source", async () => { const bindings = env(); const missing = config(); delete missing.topics["ai-models"].sources["deepmind-blog"]; assert.equal((await worker.fetch(request("/config", "PUT", missing), bindings)).status, 400); });
const validate = payload => request("/feeds/validate", "POST", payload);
async function withFetch(mock, run) { const original = globalThis.fetch; globalThis.fetch = mock; try { return await run(); } finally { globalThis.fetch = original; } }
test("validates RSS 2.0 and Atom feeds without DOMParser", async () => { await withFetch(async () => new Response('<?xml version="1.0"?><rss><channel><title>RSS Feed</title><item><link>https://example.com/a</link></item></channel></rss>', { status: 200, headers: { "Content-Type": "text/plain" } }), async () => { const response = await worker.fetch(validate({ url: "https://example.com/rss.xml", name: "RSS" }), env()); assert.equal(response.status, 200); assert.equal((await response.json()).source.name, "RSS"); }); await withFetch(async () => new Response('<?xml version="1.0"?><feed xmlns="http://www.w3.org/2005/Atom"><title>Atom Feed</title><entry><link href="https://example.com/a" /></entry></feed>', { status: 200 }), async () => assert.equal((await worker.fetch(validate({ url: "https://example.com/atom.xml" }), env())).status, 200)); });
test("rejects non-feed XML, HTML, and upstream errors", async () => { for (const response of [new Response("<?xml version=\"1.0\"?><catalog><title>No feed</title></catalog>", { status: 200 }), new Response("<html><title>HTML</title></html>", { status: 200 }), new Response("missing", { status: 404 })]) await withFetch(async () => response, async () => assert.equal((await worker.fetch(validate({ url: "https://example.com/feed" }), env())).status, 400)); });
